// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	common: {
		select: {
			/**
			 * S​e​l​e​c​t​ ​a​n​ ​o​p​t​i​o​n
			 */
			placeholder: string
		}
	}
	theme: {
		/**
		 * L​i​g​h​t
		 */
		light: string
		/**
		 * D​a​r​k
		 */
		dark: string
		/**
		 * S​y​s​t​e​m
		 */
		system: string
	}
	navigation: {
		/**
		 * M​a​i​n​ ​n​a​v​i​g​a​t​i​o​n
		 */
		label: string
		/**
		 * H​o​m​e
		 */
		home: string
		/**
		 * A​b​o​u​t​ ​m​e
		 */
		about: string
		/**
		 * B​l​o​g
		 */
		blog: string
	}
}

export type TranslationFunctions = {
	common: {
		select: {
			/**
			 * Select an option
			 */
			placeholder: () => LocalizedString
		}
	}
	theme: {
		/**
		 * Light
		 */
		light: () => LocalizedString
		/**
		 * Dark
		 */
		dark: () => LocalizedString
		/**
		 * System
		 */
		system: () => LocalizedString
	}
	navigation: {
		/**
		 * Main navigation
		 */
		label: () => LocalizedString
		/**
		 * Home
		 */
		home: () => LocalizedString
		/**
		 * About me
		 */
		about: () => LocalizedString
		/**
		 * Blog
		 */
		blog: () => LocalizedString
	}
}

export type Formatters = {}
